### ISSUE TITLE
question on permissions used

### ISSUE THREAD

**Issue by IzzySoft** [christianrowlands/android-network-survey#27]
I've just implemented additional checks with my repo recently, and when today's update of your app came in, the following report came up as a result:

```
! repo/com.craxiom.networksurvey_55.apk declares flags: usesCleartextTraffic
! repo/com.craxiom.networksurvey_55.apk declares risky permissions: android.permission.READ_CALL_LOG android.permission.READ_SMS android.permission.RECEIVE_SMS android.permission.READ_PHONE_NUMBERS
```

I've checked the app's description and the README here, but found no explanation. Can you please clarify:

* what for is access to call-logs, SMS and phone numbers needed?
* does the app reach out to any unsecured servers (not supporting SSL/https) so you need to declare `android:usesCleartextTraffic`?

Thanks in advance!

**Comment by christianrowlands** [comment]
I am not sure where the `usesCleartextTraffic` comes from as I don't set it explicitly in the app. However, it is possible it comes from the fact that the MQTT connection that can be initiated from the app supports plaintext and TLS connections. I will try setting the manifest permission to false to see if the MQTT connection still works.

As for the permissions, yes, those are risky for sure, but I use them for the CDR feature. All four of those permissions are needed for the CDR support I added about a year ago. CDR is a call detail record and is basically a log of when the phone communicates with the network. The events that are logged are incoming phone calls, outgoing phone calls, incoming and outgoing SMS messages, and serving cell changes that result in a different paging area. I have some more information on CDR logging in the [README here](https://github.com/christianrowlands/android-network-survey?tab=readme-ov-file#cdr-log-files).

Those permissions can all be denied by the user when running the app, and everything will work correctly except CDR logging.

**Comment by christianrowlands** [comment]
@IzzySoft I did some more digging and the GeoPackage library I use is what was setting `usesCleartextTraffic` to true. I added an override in my manifest to set it to false and everything still seems to be working as expected. Here is the commit that overrides the value.  https://github.com/christianrowlands/android-network-survey/commit/809d80b38b3d1ec7d019209cc566595895de12c2

**Comment by IzzySoft** [comment]
Thanks! So if I understand this code correctly, the next release won't have `cleartextTraffic` enabled in `AndroidManifest.xml` anymore, right?

**Comment by christianrowlands** [comment]
Yes, that is correct. The next release won't have that flag enabled.

**Comment by IzzySoft** [comment]
Thanks a lot! Then all is done, and I don't need to adjust the allow-list here.

**Comment by IzzySoft** [comment]
Sorry to bother you once more, @christianrowlands – but having all checks fully enabled now on my end, today's update added more to the list:

CAMERA ACCESS_COARSE_LOCATION ACCESS_FINE_LOCATION READ_PHONE_STATE BLUETOOTH_SCAN ACCESS_BACKGROUND_LOCATION READ_EXTERNAL_STORAGE*

Please let me know if I filled the gaps correctly:

```yaml
    PermIgnore:
      android.permission.ACCESS_COARSE_LOCATION: Needed to log your location during the survey.
      android.permission.ACCESS_FINE_LOCATION: Needed to log your location during the survey, especially also for GNSS constellations.
      android.permission.ACCESS_BACKGROUND_LOCATION: Needed to log your location during the survey.
      android.permission.BLUETOOTH_SCAN: Required for the feature of scanning and displaying a list of the nearby Bluetooth devices.
      android.permission.CAMERA: Required to scan QR Code for MQTT Broker connection setting.
      android.permission.READ_CALL_LOG: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.READ_SMS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.RECEIVE_SMS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.READ_PHONE_NUMBERS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.READ_PHONE_STATE: Needed to log the connection state etc. during the survey.
```

That leaves unexplained the \*_EXTERNAL_STORAGE permission (the asterisk at the end of READ_INTERNAL_STORAGE indicates that was granted implicitly because of WRITE_EXTERNAL_STORAGE). Your app requires at least Android 8 to run, do you really need the "old" storage permissions? I know up to Android 9 they are required to access media files created/owned by other apps, but is that the case here?

Thanks in advance!

**Comment by christianrowlands** [comment]
You did a pretty good job on the permissions. I added some notes after some of them, and only one is incorrect (The background one)...

```yaml
    PermIgnore:
      android.permission.ACCESS_COARSE_LOCATION: Needed to log your location during the survey. (Correct, and also to get access to the cellular details. Just knowing the serving cell means the app can have a rough idea of where the device is located)
      android.permission.ACCESS_FINE_LOCATION: Needed to log your location during the survey, especially also for GNSS constellations. (correct, and also to access Wi-Fi scans. Just knowing the Wi-Fi networks around you means you can calculate a pretty accurate location)
      android.permission.ACCESS_BACKGROUND_LOCATION: Needed to log your location during the survey. (Incorrect, I display a foreground notification so the user knows the location is being grabbed... instead, this permission is needed to allow for starting logging when the phone is booted. It is a stupid permission for that since I display the foreground notification right away, but Android does strange things sometimes. It is perfectly acceptable for users to deny this permission if they won't be using the "auto-start at boot" feature of NS.)
      android.permission.BLUETOOTH_SCAN: Required for the feature of scanning and displaying a list of the nearby Bluetooth devices. (Correct)
      android.permission.CAMERA: Required to scan QR Code for MQTT Broker connection setting. (Correct)
      android.permission.READ_CALL_LOG: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files (Correct)
      android.permission.READ_SMS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files (Correct)
      android.permission.RECEIVE_SMS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files (Correct)
      android.permission.READ_PHONE_NUMBERS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files (Correct)
      android.permission.READ_PHONE_STATE: Needed to log the connection state etc. during the survey. (Correct, and more specifically this is also needed for the phone state log file that I generate, which records every tower change to a log file... one of my favorite log files actually)
```

As for the `READ_EXTERNAL_STORAGE` permission, I added that at one point because I write to the Download directory. You are correct that in newer versions of Android I no longer need that, but for those running Android 8 and 9 it is still needed. I don't access any files from other apps, which is why I don't need it for newer Android devices. Google got smart and allow apps to only access files they create in external storage like downloads or documents, but older Android versions don't have that feature. I could try and find some older Android devices and see if I still need that permission. Maybe they released a patch for those or something.

**Comment by IzzySoft** [comment]
Woa­… that was an extensive answer, thanks a lot!

> You did a pretty good job on the permissions.

Thanks! :star_struck:

> I added some notes after some of them, and only one is incorrect (The background one)...

Oops… See, good that I asked!

I had to shorten things a bit on my end (considering where it's supposed to become visible one day) – but maybe you want to have your detailed description of those permissions and their usage somewhere in a Wiki or FAQ here? That would be excellent! You could even link to that then from the app description (Fastlane). Here I updated this to:

```yaml
    PermIgnore:
      android.permission.ACCESS_COARSE_LOCATION: Needed to log your location during the survey, and also to get access to the cellular details.
      android.permission.ACCESS_FINE_LOCATION: Needed to log your location during the survey, especially also for GNSS constellations, and also to access Wi-Fi scans.
      android.permission.ACCESS_BACKGROUND_LOCATION: Needed to allow for starting logging when the phone is booted (strangely Android seems to need it). Can be denied if the „auto-start at boot“ feature is not needed.
      android.permission.BLUETOOTH_SCAN: Required for the feature of scanning and displaying a list of the nearby Bluetooth devices.
      android.permission.CAMERA: Required to scan QR Code for MQTT Broker connection setting.
      android.permission.READ_CALL_LOG: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.READ_SMS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.RECEIVE_SMS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.READ_PHONE_NUMBERS: This is required for the CDR (Call Detail Record) feature, see https://github.com/christianrowlands/android-network-survey#cdr-log-files
      android.permission.READ_PHONE_STATE: Needed to log the connection state etc. during the survey – especially for cell tower details.
```

> but for those running Android 8 and 9 it is still needed

Trust the Google documentation… Or understand it at that. Since my scanner has all its features enabled, I learned quite a few facts from answers to my reports (remember I'm not an Android dev, so I don't encounter those nasty side-effects during coding but just see the "compressed results"). There I thought this permission was no longer needed since SAF came into being with Android 5 – but then there are so many exceptions, and different ones at that depending on your targetSDK, min SDK and different combinations of the two in conjunction with the actual onDeviceSdk :see_no_evil: Hard to keep track of all the exceptions.

So `READ_EXTERNAL_STORAGE`  is also needed to access the Downloads directory? And that cannot be done via SAF? I thought the only things not covered via SAF would be media directories.

> but older Android versions don't have that feature

Yeah. And you're expected to deduce that despite the documentation saying "if your app targets sdk 34 or higher, you need to request the media permissions **instead**". I thought I was nuts when I read that. You can have minSdk set to e.g. 20, and targetSdk to 34 – so you shall … instead? And how does Kitkat deduce the correct permissions from that then, not even ever have heard of them? Thanks for confirming I have to return those nuts :see_no_evil:

So I add:

```yaml
android.permission.READ_EXTERNAL_STORAGE: Required to access the Download folder on Android 9 and below.
```

Right? Now I need to check what downloads you need to access :see_no_evil:
